name: Static Check

on:
  push:
  workflow_call:

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
            version: latest
      - name: Run Biome
        run: biome ci .