name: Static Check

on:
  push:
  workflow_call:

jobs:
  static-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Lint with Eslint
        run: bun run check:eslint
      - name: Style check with Prettier
        run: bun run check:prettier
